# Generated by Django 4.2.10 on 2025-12-17 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[("DIFF", "Diff"), ("COMMENT", "Comment")],
                        max_length=10,
                    ),
                ),
                ("target_id", models.IntegerField()),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("SPAM", "Spam"),
                            ("ABUSE", "Abuse"),
                            ("COPYRIGHT", "Copyright Violation"),
                            ("INCORRECT", "Incorrect Information"),
                            ("SPOILER_MISLABELED", "Spoiler Mislabeled"),
                            ("OTHER", "Other"),
                        ],
                        max_length=25,
                    ),
                ),
                ("detail", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("RESOLVED", "Resolved"),
                            ("DISMISSED", "Dismissed"),
                        ],
                        default="OPEN",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
