# Generated by Django 4.2.10 on 2025-12-17 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DiffComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField()),
                (
                    "spoiler_scope",
                    models.CharField(
                        choices=[
                            ("NONE", "None (safe/high-level)"),
                            ("BOOK_ONLY", "Book Only"),
                            ("SCREEN_ONLY", "Screen Only"),
                            ("FULL", "Full (both)"),
                        ],
                        default="NONE",
                        max_length=15,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("LIVE", "Live"), ("HIDDEN", "Hidden")],
                        default="LIVE",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="DiffItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("PLOT", "Plot"),
                            ("CHARACTER", "Character"),
                            ("ENDING", "Ending"),
                            ("SETTING", "Setting"),
                            ("THEME", "Theme"),
                            ("TONE", "Tone"),
                            ("TIMELINE", "Timeline"),
                            ("WORLDBUILDING", "Worldbuilding"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "claim",
                    models.CharField(
                        help_text="Short description of the difference", max_length=200
                    ),
                ),
                (
                    "detail",
                    models.TextField(
                        blank=True, help_text="Detailed explanation (optional)"
                    ),
                ),
                (
                    "spoiler_scope",
                    models.CharField(
                        choices=[
                            ("NONE", "None (safe/high-level)"),
                            ("BOOK_ONLY", "Book Only"),
                            ("SCREEN_ONLY", "Screen Only"),
                            ("FULL", "Full (both)"),
                        ],
                        default="NONE",
                        max_length=15,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("LIVE", "Live"),
                            ("HIDDEN", "Hidden"),
                            ("LOCKED", "Locked"),
                            ("PENDING", "Pending"),
                        ],
                        default="LIVE",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DiffVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vote",
                    models.CharField(
                        choices=[
                            ("ACCURATE", "Accurate"),
                            ("NEEDS_NUANCE", "Needs Nuance"),
                            ("DISAGREE", "Disagree"),
                        ],
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "diff_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="diffs.diffitem",
                    ),
                ),
            ],
        ),
    ]
