# Generated by Django 4.2.10 on 2025-12-17 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("diffs", "0001_initial"),
        ("works", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("screen", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="diffvote",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="diff_votes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="diffitem",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_diffs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="diffitem",
            name="screen_work",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="diffs",
                to="screen.screenwork",
            ),
        ),
        migrations.AddField(
            model_name="diffitem",
            name="work",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="diffs",
                to="works.work",
            ),
        ),
        migrations.AddField(
            model_name="diffcomment",
            name="diff_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="diffs.diffitem",
            ),
        ),
        migrations.AddField(
            model_name="diffcomment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="diff_comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="diffvote",
            index=models.Index(
                fields=["diff_item", "vote"], name="diffs_diffv_diff_it_15ebd8_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="diffvote",
            unique_together={("diff_item", "user")},
        ),
        migrations.AddIndex(
            model_name="diffitem",
            index=models.Index(
                fields=["work", "screen_work"], name="diffs_diffi_work_id_ec51a1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="diffitem",
            index=models.Index(
                fields=["category"], name="diffs_diffi_categor_ba95a4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="diffitem",
            index=models.Index(fields=["status"], name="diffs_diffi_status_b9b28e_idx"),
        ),
        migrations.AddIndex(
            model_name="diffitem",
            index=models.Index(
                fields=["spoiler_scope"], name="diffs_diffi_spoiler_bdd116_idx"
            ),
        ),
    ]
