# Generated by Django 4.2.10 on 2025-12-19 03:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("screen", "0001_initial"),
        ("works", "0001_initial"),
        ("diffs", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diffcomment",
            name="status",
            field=models.CharField(
                choices=[
                    ("LIVE", "Live"),
                    ("HIDDEN", "Hidden"),
                    ("PENDING", "Pending"),
                    ("DELETED", "Deleted"),
                ],
                default="LIVE",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="diffitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("LIVE", "Live"),
                    ("HIDDEN", "Hidden"),
                    ("LOCKED", "Locked"),
                    ("PENDING", "Pending"),
                    ("REJECTED", "Rejected"),
                    ("FLAGGED", "Flagged"),
                ],
                default="LIVE",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="ComparisonVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("has_read_book", models.BooleanField(default=False)),
                ("has_watched_adaptation", models.BooleanField(default=False)),
                (
                    "preference",
                    models.CharField(
                        choices=[
                            ("BOOK", "Book"),
                            ("SCREEN", "Screen Adaptation"),
                            ("TIE", "Tie / Depends"),
                            ("DIDNT_FINISH", "Didn't finish both"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "faithfulness_rating",
                    models.IntegerField(
                        blank=True,
                        help_text="How faithful is the adaptation? (1=Completely different, 5=Very faithful)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "screen_work",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comparison_votes",
                        to="screen.screenwork",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comparison_votes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "work",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comparison_votes",
                        to="works.work",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["work", "screen_work"],
                        name="diffs_compa_work_id_0f3911_idx",
                    ),
                    models.Index(
                        fields=["preference"], name="diffs_compa_prefere_1de324_idx"
                    ),
                ],
                "unique_together": {("work", "screen_work", "user")},
            },
        ),
    ]
