# Generated by Django 4.2.10 on 2025-12-23 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("diffs", "0003_alter_diffcomment_status_alter_diffitem_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="diffcomment",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="diffs.diffcomment",
            ),
        ),
    ]
