# Generated by Django 4.2.10 on 2025-12-25 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diffs", "0004_diffcomment_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="diffitem",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Optional image to illustrate the difference (max 5MB)",
                null=True,
                upload_to="diff_images/",
            ),
        ),
    ]
