# Generated by Django 4.2.27 on 2025-12-31 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diffs", "0005_diffitem_image"),
    ]

    operations = [
        migrations.AddIndex(
            model_name='diffcomment',
            index=models.Index(fields=['diff_item', 'status'], name='diffs_diffc_diff_it_idx'),
        ),
        migrations.AddIndex(
            model_name='diffcomment',
            index=models.Index(fields=['user', '-created_at'], name='diffs_diffc_user_cr_idx'),
        ),
        migrations.AddIndex(
            model_name='diffcomment',
            index=models.Index(fields=['status'], name='diffs_diffc_status_idx'),
        ),
    ]
