# Generated by Django 4.2.10 on 2025-12-17 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("works", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScreenWork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("MOVIE", "Movie"), ("TV", "TV Series")], max_length=10
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("slug", models.SlugField(max_length=500, unique=True)),
                ("summary", models.TextField(blank=True)),
                ("year", models.IntegerField(blank=True, null=True)),
                (
                    "wikidata_qid",
                    models.CharField(
                        blank=True, db_index=True, max_length=20, null=True, unique=True
                    ),
                ),
                (
                    "tmdb_id",
                    models.IntegerField(
                        blank=True, db_index=True, null=True, unique=True
                    ),
                ),
                ("poster_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["title"], name="screen_scre_title_b67727_idx"),
                    models.Index(
                        fields=["type", "year"], name="screen_scre_type_1e5bc4_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AdaptationEdge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relation_type",
                    models.CharField(
                        choices=[
                            ("BASED_ON", "Based On"),
                            ("INSPIRED_BY", "Inspired By"),
                            ("LOOSELY_BASED", "Loosely Based On"),
                        ],
                        default="BASED_ON",
                        max_length=20,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("WIKIDATA", "Wikidata"), ("MANUAL", "Manual")],
                        default="WIKIDATA",
                        max_length=20,
                    ),
                ),
                ("confidence", models.SmallIntegerField(default=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "screen_work",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_works",
                        to="screen.screenwork",
                    ),
                ),
                (
                    "work",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adaptations",
                        to="works.work",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["work", "screen_work"],
                        name="screen_adap_work_id_5db0b5_idx",
                    )
                ],
                "unique_together": {("work", "screen_work")},
            },
        ),
    ]
