# Generated by Django 4.2.10 on 2025-12-24 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screen", "0002_screenwork_tmdb_popularity"),
    ]

    operations = [
        migrations.AddField(
            model_name="screenwork",
            name="genres",
            field=models.JSONField(
                blank=True, default=list, help_text="Full list of genres from TMDb"
            ),
        ),
        migrations.AddField(
            model_name="screenwork",
            name="primary_genre",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Primary genre from TMDb (first in list)",
                max_length=100,
            ),
        ),
    ]
