# Generated by Django 4.2.10 on 2025-12-28 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screen", "0003_add_genre_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="screenwork",
            name="backdrop_path",
            field=models.URLField(
                blank=True,
                help_text="TMDb backdrop image URL for cinematic hero backgrounds",
            ),
        ),
    ]
