# Generated by Django 4.2.10 on 2025-12-29 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screen", "0004_screenwork_backdrop_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="screenwork",
            name="dominant_color",
            field=models.CharField(
                blank=True,
                help_text="Hex color extracted from poster (e.g., #3b82f6)",
                max_length=7,
            ),
        ),
    ]
