# Generated by Django 4.2.10 on 2025-12-30 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screen", "0005_add_dominant_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="screenwork",
            name="watch_providers",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="TMDb watch provider data by country (streaming, rent, buy)",
            ),
        ),
    ]
