# Generated by Django 4.2.10 on 2025-12-30 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screen", "0006_screenwork_watch_providers"),
    ]

    operations = [
        migrations.AddField(
            model_name="screenwork",
            name="director",
            field=models.CharField(
                blank=True,
                help_text="Primary director from TMDb credits",
                max_length=200,
            ),
        ),
    ]
