# Generated by Django 4.2.10 on 2025-12-30 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screen", "0007_screenwork_director"),
    ]

    operations = [
        migrations.AddField(
            model_name="screenwork",
            name="average_rating",
            field=models.FloatField(
                blank=True,
                help_text="Average rating from TMDb (vote_average)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="screenwork",
            name="ratings_count",
            field=models.IntegerField(
                blank=True,
                help_text="Number of ratings from TMDb (vote_count)",
                null=True,
            ),
        ),
    ]
