# Generated by Django 4.2.10 on 2025-12-20 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("works", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="work",
            name="author",
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name="work",
            name="genre",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
