# Generated by Django 4.2.10 on 2025-12-28 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("works", "0003_enable_pg_trgm"),
    ]

    operations = [
        migrations.AddField(
            model_name="work",
            name="average_rating",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=2, null=True
            ),
        ),
        migrations.AddField(
            model_name="work",
            name="ratings_count",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
