# Generated by Django 4.2.10 on 2025-12-24 03:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("diffs", "0004_diffcomment_parent"),
        ("users", "0002_bookmark"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("BADGE_EARNED", "Badge Earned"),
                            ("REPUTATION_MILESTONE", "Reputation Milestone"),
                            ("DIFF_CONSENSUS", "Difference Reached Consensus"),
                            ("COMMENT_REPLY", "Comment Reply"),
                            ("COMMENT_HELPFUL", "Comment Marked Helpful"),
                            ("DIFF_VALIDATED", "Difference Validated"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("action_url", models.CharField(blank=True, max_length=500)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReputationEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("DIFF_CREATED", "Difference Created"),
                            ("DIFF_ACCURATE", "Difference Marked Accurate"),
                            ("DIFF_CONSENSUS_HIGH", "High Consensus Achieved"),
                            ("DIFF_CONSENSUS_MODERATE", "Moderate Consensus Achieved"),
                            ("DIFF_REJECTED", "Difference Rejected"),
                            ("DIFF_SOURCE_ADDED", "Source Added to Difference"),
                            ("COMMENT_CREATED", "Comment Created"),
                            ("COMMENT_HELPFUL", "Comment Marked Helpful"),
                            ("VOTE_CAST", "Vote Cast"),
                            ("CONTRIBUTION_REPORTED", "Contribution Reported"),
                            ("CONTRIBUTION_REMOVED", "Contribution Removed"),
                        ],
                        max_length=50,
                    ),
                ),
                ("amount", models.IntegerField()),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserBadge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "badge_type",
                    models.CharField(
                        choices=[
                            ("FIRST_VOTE", "First Vote"),
                            ("FIRST_COMMENT", "First Comment"),
                            ("FIRST_DIFF", "First Difference"),
                            ("VOTER_10", "10 Votes"),
                            ("VOTER_50", "50 Votes"),
                            ("VOTER_100", "100 Votes"),
                            ("COMMENTER_10", "10 Comments"),
                            ("COMMENTER_50", "50 Comments"),
                            ("DIFF_CREATOR_5", "5 Differences"),
                            ("DIFF_CREATOR_25", "25 Differences"),
                            ("WELL_SOURCED", "Well-Sourced"),
                            ("HIGH_ACCURACY", "High Accuracy"),
                            ("CONSENSUS_BUILDER", "Consensus Builder"),
                            ("EDITOR", "Editor"),
                            ("HELPFUL_COMMENTER", "Helpful Commenter"),
                            ("EARLY_ADOPTER", "Early Adopter"),
                            ("GENRE_SPECIALIST_HORROR", "Horror Specialist"),
                            ("GENRE_SPECIALIST_SCIFI", "Sci-Fi Specialist"),
                            ("GENRE_SPECIALIST_FANTASY", "Fantasy Specialist"),
                            ("SERIES_SPECIALIST", "Series Specialist"),
                            ("ACTIVE_CONTRIBUTOR", "Active Contributor"),
                            ("WEEKLY_CONTRIBUTOR", "Weekly Contributor"),
                        ],
                        max_length=50,
                    ),
                ),
                ("earned_at", models.DateTimeField(auto_now_add=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-earned_at"],
            },
        ),
        migrations.RenameIndex(
            model_name="bookmark",
            new_name="users_bookm_user_id_636448_idx",
            old_name="users_bookm_user_id_b8c5e4_idx",
        ),
        migrations.AddField(
            model_name="userbadge",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="badges",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="reputationevent",
            name="comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="diffs.diffcomment",
            ),
        ),
        migrations.AddField(
            model_name="reputationevent",
            name="diff_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="diffs.diffitem",
            ),
        ),
        migrations.AddField(
            model_name="reputationevent",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reputation_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="reputationevent",
            name="vote",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="diffs.diffvote",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="badge",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.userbadge",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="diffs.diffcomment",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="diff_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="diffs.diffitem",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="userbadge",
            index=models.Index(
                fields=["user", "-earned_at"], name="users_userb_user_id_6f17c8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userbadge",
            index=models.Index(
                fields=["badge_type"], name="users_userb_badge_t_abbc3f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userbadge",
            unique_together={("user", "badge_type")},
        ),
        migrations.AddIndex(
            model_name="reputationevent",
            index=models.Index(
                fields=["user", "-created_at"], name="users_reput_user_id_342f40_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reputationevent",
            index=models.Index(
                fields=["event_type"], name="users_reput_event_t_295071_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "is_read", "-created_at"],
                name="users_notif_user_id_f3f50a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["notification_type"], name="users_notif_notific_af6ddd_idx"
            ),
        ),
    ]
