# Generated by Django 4.2.27 on 2026-01-08 09:28

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_notification_reputationevent_userbadge_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "genres",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        blank=True,
                        default=list,
                        help_text="List of genre preferences",
                        size=None,
                    ),
                ),
                (
                    "book_vs_screen",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BOOKS", "Prefer Books"),
                            ("EQUAL", "Enjoy Both Equally"),
                            ("SCREEN", "Prefer Adaptations"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "contribution_interest",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ADD_DIFFS", "Point out differences"),
                            ("DISCUSS", "Discuss with others"),
                            ("EXPLORE", "Just exploring"),
                        ],
                        max_length=50,
                    ),
                ),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "User preferences",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="onboarding_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="onboarding_completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="onboarding_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="onboarding_step",
            field=models.IntegerField(
                choices=[
                    (0, "Not Started"),
                    (1, "Username Selection"),
                    (2, "Interest Quiz"),
                    (3, "Suggested Comparisons"),
                    (4, "Complete"),
                ],
                default=0,
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["username"], name="auth_user_usernam_f2740e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("username"),
                name="unique_lower_username",
                violation_error_message="Username already exists (case-insensitive)",
            ),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="preferences",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="userpreferences",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["genres"], name="users_userp_genres_fc5eb7_gin"
            ),
        ),
    ]
